name: check
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        uses: kevincobain2000/action-gobrew@v2
        with:
          version: latest
      -
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
      - 
        run: go test ./...
        shell: bash
      - 
        run: go build .
        shell: bash
