on:
  push:
  pull_request:
  workflow_dispatch:

name: "Build"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        uses: kevincobain2000/action-gobrew@v2
        with:
          version: latest
      - 
        name: Build
        run: go build .
        shell: bash