name: check
on:
  pull_request:
    branches: [main]
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        uses: kevincobain2000/action-gobrew@v2
        with:
          version: latest
      -
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.2.0
      - 
        run: go test ./...
        shell: bash
      - 
        run: go build .
        shell: bash
